### ISSUE TITLE
Add version numbers

### ISSUE THREAD

**Issue by nichtich** [programmfabrik/coffeescript-ui#3]
The current repository does not include version numbers so it is hard to find out which state of CUI is being shipped with a given version of easyDB and to state which version(s) of CUI a custom plugin has been developed for and tested against. Please add version numbers, at least as git tags. A CHANGES file with versions and description of changes would be even better.

Internal ticket: https://tickets.programmfabrik.de/ticket/38978

**Comment by martinrode** [comment]
Jacob, the CUI submodule reference in the EZ5 branch is exactly for that. Open the EZ5 App and under menu -> easydb (bottom) you find the CUI GIT reference number. Hope that helps for now.

**Comment by nichtich** [comment]
Thanks! This solves part of the problem if we include CUI as git submodule *in every plugin* and always refer to to the oldest required version. I did so in

https://github.com/programmfabrik/easydb-custom-data-type-link/commit/043308167d8c46bda5e1e5e6106c92dc7079d571

do you agree in managing dependencies of custom data types this way?

Still it's inconvenient to look up because one cannot easily see whether a the CUI requirement is older or newer than a given state. Version numbers and changelog are required for proper release management and dependency control anyway, so I'd keep this ticket open with less urgency.

**Comment by KlausThornProgrammfabrik** [comment]
Thanks for your input. for further discussion and issues, please write to support@programmfabrik.de
