### ISSUE TITLE
Deploy built documentation?

### ISSUE THREAD

**Issue by kba** [programmfabrik/coffeescript-ui#4]
Can you make the built documentation available? E.g. in a gh-pages branch in this repository, so it would be available at https://coffeescript-ui.github.io? http://picshare.5.easydb.de/cui/demo/#Documentation seems broken (`not found (error.user.url_not_found)`).

Thanks!

**Comment by kba** [comment]
See https://kba.github.io/coffeescript-ui.

* Create a new orphan branch `gh-pages`
* `make docs`
* copy `doc` somewhere else
* Remove all files from working tree
* Add contents of `doc`.
* Push

**Comment by romanglom** [comment]
Hello @kba 
We have the build documentation available at [README](https://github.com/programmfabrik/coffeescript-ui/blob/master/README.md)

Also, we are working in the [Documentation](https://programmfabrik.gitbooks.io/coffeescript-ui/) (It's not finished yet) and a [Tutorial](https://programmfabrik.gitbooks.io/coffeescript-ui/tutorial/tutorial.html)
